# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  j17:
    docker:
      - image: 'cimg/openjdk:17.0'

orbs: 
  maven: circleci/maven@1.2.0

workflows:
  maven-build-test:
    jobs:
      - maven/test:
          executor: j17
